### ISSUE TITLE
› Deezer doesn't provide the song anymore [Not fixed on update]

### ISSUE THREAD

**Issue by flioner** [d-fi/releases#10]
When I chose any song it gives me this error message.

The previous troubleshooting advice you gave was that the problem was a slow internet connection or that the user wasn't using a VPN.

I currently am in a 150mbps network so it isnt the internet speed, is there a solve to this issue without a VPN. Since upgrading to the latest version sadly didnt solve the problem.

**Comment by sayem314** [comment]
Sounds like your arl expired. You need to refresh it. Please follow this discussion here:
https://t.me/dFiCommunity/3621
