### ISSUE TITLE
✖  fatal     Request failed with status code 500

### ISSUE THREAD

**Issue by FranOjedaCMusic** [d-fi/releases#13]
Hey there! Thank you alot for the yesterday update, i was able to use it flawless on windows but on mac it give me the following error even with the same tracks i was able to download on win

✖  fatal     Request failed with status code 500

**Comment by FranOjedaCMusic** [comment]
Update: I'm getting the same error in windows

**Comment by sayem314** [comment]
Can you paste `d-fi.log`?

**Comment by FranOjedaCMusic** [comment]
Hey, everything is working fine rn, idk what happened
