### ISSUE TITLE
Unexpected token % in JSON at position 9

### ISSUE THREAD

**Issue by jbeckham149** [d-fi/releases#16]
Getting this error randomly. I updated to the latest version and tried to get another ARL cookie, but it seems like this error still appears and I cannot download anything.

![d-fi_bH1SC5AIQ5](https://user-images.githubusercontent.com/69279426/99070378-19916c80-257e-11eb-9395-888eba600513.png)

**Comment by sayem314** [comment]
Fixed on v1.3.9
