### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by augustobob** [d-fi/releases#17]
Please, make a way to keep the song separated in their folders when downloading a playlist, all the songs in the same folder is a big mess to organize.

**Comment by augustobob** [comment]
Folders could be like
Artist> Album> Track
and / or for playlists
Playlist> Artist> Album> Track

**Comment by justfoolingaround** [comment]
I'm quite sure you can configure the save layout to get the desired file structure. Check out [this.](https://notabug.org/sayem314/d-fi/src/master/docs/config.md) _(oh my bad, I didn't check the date on this one but I'll let it stay here just in case someone wonders about the same thing again)_

**Comment by sayem314** [comment]
> I'm quite sure you can configure the save layout to get the desired file structure. Check out [this.](https://notabug.org/sayem314/d-fi/src/master/docs/config.md)

Yes right.

 _(oh my bad, I didn't check the date on this one but I'll let it stay here just in case someone wonders about the same thing again)_

No matter how old the issue is, as long as it's open and unresolved, you are welcome to discuss it.

**Comment by sayem314** [comment]
> @augustobob Folders could be like
> Artist> Album> Track

You can do this on the new v2 beta either from the configuration file or cli. For cli you can run:
 `d-fi -o "{ART_NAME}/{ALB_NAME}/{SNG_TITLE}" url_here`

> and / or for playlists
> Playlist> Artist> Album> Track

You can do this with config or cli: `d-fi -o "Playlist/{ART_NAME}/{ALB_NAME}/{SNG_TITLE}" url_here`

**Comment by augustobob** [comment]
Thank you very much for let me know about this and for the sample. It helped me a lot now.
