### ISSUE TITLE
Deezer doesn't provide the song anymore.

### ISSUE THREAD

**Issue by th4tkh13m** [d-fi/releases#18]
Well, I know this problem occurs when the connection is timeout or Deezer have patched their servers. My connection is fined so I think they patched it.

**Comment by th4tkh13m** [comment]
![image](https://user-images.githubusercontent.com/29520244/103629468-eca47900-4f72-11eb-9b81-2311f1ff4411.png)

**Comment by sayem314** [comment]
You need to update arl cookie `d-fi -a your_arl`

**Comment by th4tkh13m** [comment]
Thank you! I will close this issue.
