### ISSUE TITLE
Deezer doesn't provide song anymore

### ISSUE THREAD

**Issue by gcbspender** [d-fi/releases#19]
Last few days whenever I put a link from Deezer into d-fi, it finds it and starts to download but then finishes with Fatal Errors on every song stating that 'Deezer doesn't provide the song anymore'.  I have tried several different albums from many artists.

**Comment by z3huti** [comment]
> Last few days whenever I put a link from Deezer into d-fi, it finds it and starts to download but then finishes with Fatal Errors on every song stating that 'Deezer doesn't provide the song anymore'. I have tried several different albums from many artists.

https://github.com/d-fi/releases/issues/18

**Comment by gcbspender** [comment]
Awesome, thank you!  Didn't realize I had to do that, previously was never an issue.  For those stumbling upon this with same issue follow these directions - Get token from cookie


Use Google Chrome and log in to your Deezer account (Create a free account if you don’t have one already).

When logged in click, View> Developer>Developer Tools to open up Google Chrome’s developer settings.
Go to Application in the top-menu and expand Coockies in the left menu. Then click on https://www.doozer.com.
Find arl and copy it’s value. This can be done by marking it and right click, then Edit Value. Copy the value.


Example on token:
555c699f5fbd1caab8dfef52ffcfef107c75845afd7448967da2672492fb338a868fe27d9364fa9144f06988dbb54548c07004467b912ceb179eea85167d0fb54e3a6aa9efd51535b5d7619c790461c35210c16cdd2d09b29cf29bc0953086a4

Then in terminal or Cmd use this - `/PATH TO FOLDER/d-fi\ downloads/d-fi d-fi -a YOUR ARL COPIED ABOVE`

**Comment by kunambi** [comment]
This information should preferably be in the documentation
