### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by Gamer4Life2020** [d-fi/releases#20]
Thanks on the new v2 update love it so far. However, on the search say like 50 cent where there are explicit and edited tracks. The search only list one if there are explicit and edited versions which does it download or does it download both? I normally make a list or do each one separately so not an issue but do like the search option and just wondering how it works.

Thanks

**Comment by sayem314** [comment]
Glad you are enjoying beta! Let me know if you find any issues so I can fix them before the final release. Back to your question, whenever you search or paste links you will be prompted to select tracks you want to download (you can press `a` to toggle selection of all items). Now if you select tracks with multiple version it will download them all assuming there are differences in the title.

**Comment by Gamer4Life2020** [comment]
Ok will do. I'm also very interested in the Tidal aspect as I'm currently using TMDler both EXE and Python and work for the most part but have issues more often than not. So can help with that as well at least checking in MQA/ATOMS works or not depending if implemented.

**Comment by sayem314** [comment]
Tidal support is not original. Like before it will be downloaded from Deezer via matching song exact ISRC code. There are plenty of tools available to download from the Tidal source and it's possible to add support on `d-fi` as well but I am not interested to do so. The main goal of `d-fi` is to _deezerify_ everything,

**Comment by sayem314** [comment]
Tidal support is now available on the beta 3
