### ISSUE TITLE
d-fi v2 difference in files

### ISSUE THREAD

**Issue by Darthohh** [d-fi/releases#21]
Firstly I wanna thank you for the new beta release, it looks amazing with the new download bar and I was amazed with the fast downloading time of large playlists. Secondly I'm comparing two music files (same song) from the v1.3.10 d-fi and the new beta and I'm finding that the old d-fi song has: Year, Genre, (# song sequence in album) and Publisher all in details in the file, so I'm wondering if you can add them later. Thirdly can you add an option to select between adding the name of the playlist to the file name or not?

Thanks

**Comment by sayem314** [comment]
Good catch! The last time Deezer updated their API they reduced some info from track details and I patched this with additional calls on v1. I will re-implement this on v2.

I'm not sure what did you mean by  `can you add an option to select between adding the name of the playlist to the file name or not?`. Can you please elaborate more?

You can speed up download speed even faster via increasing concurrency, by default, it is set to `4`. Here is an example to increase it `d-fi -c 8` or `d-fi -q 320 -c 10 url_here`. Don't go above 50, there are rate limits on the Deezer side.

**Comment by Darthohh** [comment]
I tried downloading one playlist; all songs were downloaded perfectly but all the names of the file songs were "the playlist name followed by the song name", so I'm wondering if you can add an option to disable adding the playlist name followed by the song name to each song filename. In terms of the download speed I will look it up.
Much appreciated

**Comment by sayem314** [comment]
Playlist tracks shouldn't include playlist title in it. By default this is how it should be saved --> `Playlist/{TITLE}/{SNG_TITLE}` <-- where `{TITLE}` is playlist title and `{SNG_TITLE}` is tracks titles. Here is an example of saved file structure --> `Playlist/Daft punk Random Access memories/11 - Fragments of Time (feat. Todd Edwards).mp3`. I'm still not sure how it is being saved for you.

You can also modify the save layout via changing config. To change it, create `d-fi.config.json` in the same folder you run `d-fi` from with this contents.

```
saveLayout: {
  track: 'Music/{ALB_TITLE}/{SNG_TITLE}',
  album: 'Music/{ALB_TITLE}/{SNG_TITLE}',
  artist: 'Music/{ALB_TITLE}/{SNG_TITLE}',
  playlist: 'Playlist/{TITLE}/{SNG_TITLE}',
}
```

**Comment by Darthohh** [comment]
ok so for example I'm downloading a playlist called Retro, the filename of each song is being called "PlaylistRetro01 - Bad.mp3", second song "PlaylistRetro01 - Dancing Queen.mp3" and so on..

**Comment by sayem314** [comment]
This is really weird. It shouldn’t happen. Can you confirm if it’s not specific to that playlist? What version and kind of OS are you using?

**Comment by Darthohh** [comment]
Tried another Playlist (https://open.spotify.com/playlist/4V1OqLIowZVQEM3YyXwYgY?si=41d7ae7fcad849c6) and the first song is being called "PlaylistTate McRae Complete01 - all my friends are fake.mp3" and so on..
Windows 10 Version 20H2

**Comment by sayem314** [comment]
Thanks! I have tried this now on Linux and everything is working as expected. This is Windows specific issue and I don’t have Windows anymore but don’t worry I will boot windows with virtual machine tomorrow and debug this further and will get it fixed. Thanks again for reporting with required details.

**Comment by sayem314** [comment]
Beta 3 released with a fix for save layout and improvements with tagging. Let me know if you still have issues.

**Comment by Darthohh** [comment]
In terms of save layout and metadata tagging it has been fixed perfectly. But just a note will you add an error message to songs that couldn't be founded/downloaded, because in the previous playlist I tagged it had 25 songs and when I tried downloading it It downloaded 24 songs and just closed the program. I can't find any error messages shown in the terminal in case there is an error in downloading.

Also you mentioned I can increase concurrency and modify the save layout via "d-fi.config.json" but I can't seem to find it; I'm only finding v1.3.10 files. I'm using the beta via downloading "d-fi-win.zip".

**Comment by sayem314** [comment]
Thanks for your input. In windows it does exit after it’s done and I should keep the tab open so user can see messages.

v2 configuration is bit different than v1. Read more about it [here](https://notabug.org/sayem314/d-fi/src/master/docs/config.md)
