### ISSUE TITLE
 beta with d-fi.config.json

### ISSUE THREAD

**Issue by z3huti** [d-fi/releases#22]
In windows, opening d-fi beta with d-fi.config.json, it opens and closes immediately.

**Comment by sayem314** [comment]
Can you run with windows cmd a take a look at the error message? Hold left `shift` on the folder `d-fi.exe` is and right-click on mouse and then click `open cmd here`. Once cmd is opened type `d-fi.exe` and hit enter.

**Comment by z3huti** [comment]
i get this

undefined:2
  concurrency: 4,
  ^

SyntaxError: Unexpected token c in JSON at position 5
    at JSON.parse (<anonymous>)
    at new Config (C:\snapshot\d-fi\dist\src\lib\config.js:30:43)
    at Object.<anonymous> (C:\snapshot\d-fi\dist\src\d-fi.js:36:14)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at internal/main/run_main_module.js:17:47


JSON  looks like this

{
  concurrency: 4,
  saveLayout: {
    track: 'Music/{ALB_TITLE}/{SNG_TITLE}',
    album: 'Music/{ALB_TITLE}/{SNG_TITLE}',
    artist: 'Music/{ALB_TITLE}/{SNG_TITLE}',
    playlist: 'Playlist/{TITLE}/{SNG_TITLE}',
  },
  trackNumber: true,
  coverSize: {
    '128': 500,
    '320': 500,
    flac: 1000,
  },
  
}

**Comment by sayem314** [comment]
Can you upload your config file here instead of pasting it? I need to take a look. It seems like a parsing error.

**Comment by z3huti** [comment]
sure

[d-fi.config.json.zip](https://github.com/d-fi/releases/files/6116527/d-fi.config.json.zip)

**Comment by z3huti** [comment]
it works now.

i let the program make JSON file, and btw it looks a bit different from whats on this link sugested https://notabug.org/sayem314/d-fi/src/master/docs/config.md

it should be like this 


{
  "concurrency": 4,
  "saveLayout": {
    "track": "Music/{ALB_TITLE}/{SNG_TITLE}",
    "album": "Music/{ALB_TITLE}/{SNG_TITLE}",
    "artist": "Music/{ALB_TITLE}/{SNG_TITLE}",
    "playlist": "Playlist/{TITLE}/{SNG_TITLE}"
  },
  "trackNumber": true,
  "coverSize": {
    "128": 500,
    "320": 500,
    "flac": 1000
  },
  "cookies": {
    "arl": "xxxxxxxxxx"
  }
}


concurrency, saveLayout and so on should be between " "

**Comment by sayem314** [comment]
Yes sorry. JSON should have quotes. I will update the docs. Thanks!
