### ISSUE TITLE
track not available

### ISSUE THREAD

**Issue by augustobob** [d-fi/releases#24]
some musics return this error. This playlist have some https://www.deezer.com/br/playlist/8778996062

**Comment by sayem314** [comment]
investigating...

**Comment by sayem314** [comment]
The track is unavailable but there is a fallback (alternative) track available. v2 beta doesn't fall back while v1 does. This will be re-implemented on beta 11 (next version).

**Comment by sayem314** [comment]
This has been fixed now with the beta 11 release. Thanks for the report :)

**Comment by augustobob** [comment]
Thanks, I’ll keep trying d-fi. 😊
