### ISSUE TITLE
albums remixes and tags

### ISSUE THREAD

**Issue by z3huti** [d-fi/releases#25]
albums remixes, all files (for mp3 and flac) get same file names, tags too (mp3 and flac), this one for example https://www.deezer.com/us/album/212694892

_"in flac, tag YEAR gets added two times, so you get 2021 and 2021-03-12 (thats what i see in mp3tag program)
for mp3 is ok, only one YEAR tag"_ - not irrelevant anymore, its and mp3tag issue 

some albums that have songs from different albums are getting into different maps

example https://www.deezer.com/us/album/99691942

**Comment by sayem314** [comment]
This has been fixed now with the beta 11 release. Thanks for the report :)
