### ISSUE TITLE
Spotify Playlist Download

### ISSUE THREAD

**Issue by Bluestar98** [d-fi/releases#3]
First, absolutely amazing tool! 

My Problem, when feeding a Spotify Playlist URL it starts the Download and creates mp3 Files. When the last mp3 File gets downloaded it deletes the content of all Folders. Workaround abort the Script at the last mp3 file then the mp3 files will stay in the correct folders.

**Comment by sayem314** [comment]
It’s really not an issue. Playlist are moved to separate folder by default. You can avoid this via changing `playlistRoot` same as `root` inside `config.json` on your user config folder.

**Comment by sayem314** [comment]
In v2 beta `d-fi` behaves differently than v1. Let me know if you can reproduce this in the latest beta release.
