### ISSUE TITLE
adding other Metadata to the folder name?

### ISSUE THREAD

**Issue by Atari215** [d-fi/releases#30]
think it would be at all possible to pull from the Metadata and add isrc/label/genre etc to the source folder name? or is it already implemented and I'm just a dummy(Dont have much time these days to go through all the code and see what functions you have tinkered with lol)? Also possibly a parameter like other modules have that will crossreference the Metadata, file properties & checksums to prevent duplicates?

**Comment by augustobob** [comment]
pretty sure this is an option already, just dont know how to use. i need help to use config files and changing arl for mine to be able to download 320, flac again

**Comment by sk8ordi3** [comment]
> pretty sure this is an option already, just dont know how to use. i need help to use config files and changing arl for mine to be able to download 320, flac again

**here is the basic template with arl .json**
https://notabug.org/sayem314/d-fi/src/master/docs/config.md


```
{
  "concurrency": 4,
  "saveLayout": {
    "track": "Music/{ALB_TITLE}/{SNG_TITLE}",
    "album": "Music/{ALB_TITLE}/{SNG_TITLE}",
    "artist": "Music/{ALB_TITLE}/{SNG_TITLE}",
    "playlist": "Playlist/{TITLE}/{SNG_TITLE}"
  },
  "playlist": {
    "resolveFullPath": false
  },
  "trackNumber": true,
  "fallbackTrack": true,
  "fallbackQuality": true,
  "coverSize": {
    "128": 500,
    "320": 500,
    "flac": 1000
  },
  "cookies": {
    "arl": "xxx..."
  }
}
```

**Comment by nkeor** [comment]
Any field available on the songType interface can be used on the download layout: https://github.com/d-fi/d-fi-core/blob/4ff25adeaa26408788e42836f3449636af9c1d16/src/types/tracks.ts#L23
