### ISSUE TITLE
Your account can't stream MP3_320 tracks

### ISSUE THREAD

**Issue by tadeomoon** [d-fi/releases#32]
Hi! I've been having this issue for a couple of weeks now with the latest version.
Both my Spotify and Deezer account are premium, but I keep getting this error message.
I only managed to download tracks on 144 kbps quality, which is of no use for me right now.
Is it a problem with my accounts? Are they not correctly synced?
How can I fix this?
I'm kind of in a hurry
Thank you! and thank you for this amazing tool and all the work you put into it!

**Comment by nkeor** [comment]
I'll link you to a comment by me over at https://github.com/d-fi/releases/issues/28#issuecomment-912853663.

You do need to set d-fi's ARL to your account's for 320kbps/FLAC downloads to work: https://notabug.org/sayem314/d-fi
(TL;DR: run `d-fi -a YOUR_ARL`).
Make sure you're really using your arl, and that your account is Premium/HiFi.

**Comment by tadeomoon** [comment]
This fiexed it! Not an app issue
Thanks for the support on the Telegram community!
