### ISSUE TITLE
User Auth Required

### ISSUE THREAD

**Issue by sethandroo** [d-fi/releases#34]
Attempted to use the newest version (2.1.2) and upon launch it crashes (Windows 10). Tried opening using PowerShell and this is the error message it returns:

● pending Verifying session...
✖ error NEED_USER_AUTH_REQUIRED,Require user auth

**Comment by th4tkh13m** [comment]
You must set your account's ARL. Just check #19 to know how to set one. Otherwise, you can just update to the new version, 2.1.3 as the old ARL expired.
