### ISSUE TITLE
No longer downloads in FLAC

### ISSUE THREAD

**Issue by Joao13Traducoes** [d-fi/releases#37]
When downloading in FLAC format, all tracks give error and appears on all "Your account can't stream FLAC tracks".

**Comment by nkeor** [comment]
https://github.com/d-fi/releases/issues/28#issuecomment-912853663

You need a HiFi account to download FLAC tracks

**Comment by BlueMan1986** [comment]
How can I add my ARL in app? Is there an option? If not, can you make that in next update... Thx

**Comment by nkeor** [comment]
`d-fi.exe -a ARL`
Replace `ARL` with your actual ARL
On Linux or Mac, `./d-fi -a ARL`

**Comment by BlueMan1986** [comment]
How do I find where is track available, in witch country?
for example this one..
✖ error Being Evil Has a Price (Opening Theme from "Lucifer") [Cover]
  → This track is not available in your country (RS)

**Comment by nkeor** [comment]
I don't know, sorry.
It's better to have this kind of discussions on Telegram tho: https://t.me/dFiCommunity
@Joao-13 you can close this issue can be closed as it isn't really an issue
