### ISSUE TITLE
can't download playlists

### ISSUE THREAD

**Issue by tadeomoon** [d-fi/releases#38]
Hello! I've been encountering this issue when trying to download playlists from Spotify
After pasting the link, terminal reads the following:

✖ error An error occurred while communicating with Spotify's Web API.
Details: Not found..

This only happens when trying to download playlists from Spotify.
D-Fi still works for albums and songs

I'm running the latest update on a MacBook Air M1 with Big Sur 11.3.1

**Comment by nkeor** [comment]
Is this still reproducible?

**Comment by tadeomoon** [comment]
hey! good to hear from you
This issue has been solved, I think it maybe had to do with the playlists being private.
Forgot to take it down, I'm so sorry
feel free to do so
I'll report any other issues I encounter
Thanks a lot!
