### ISSUE TITLE
Cannot read property 'OPTIONS' of undefined

### ISSUE THREAD

**Issue by Mrakobes666** [d-fi/releases#40]
https://www.deezer.com/ru/album/209246322

At the same time, the album is being played, I did not change the settings and downloaded it yesterday

**Comment by nkeor** [comment]
Working fine over here...
Maybe d-fi's default ARL expired?
Try setting the arl to yours with `./d-fi -a ARL` on Linux/Mac or `d-fi.exe -a ARL` on Win.

**Comment by MrSanglier** [comment]
Yep, can confirm it's a dead ARL issue.
