### ISSUE TITLE
320 kbit download issue

### ISSUE THREAD

**Issue by CYigit** [d-fi/releases#47]
Hello. Only 128 kbit and FLAC options work while downloading music. Is 320 kbit option fixable?

**Comment by nkeor** [comment]
Please provide a bit more info on how it isn't working.

**Comment by CYigit** [comment]
If I select 320 kbit at start, this error shows up when I want to download a song:

![image](https://user-images.githubusercontent.com/84289698/161397075-42fc2e2a-a6bf-4c7e-b6bc-62c9fae5f146.png)

**Comment by nkeor** [comment]
Well with d-fi's default account you won't be able to download anything other than mp3 128kbps. You need a Deezer Premium account for 320kbps and HiFi for FLAC

**Comment by CYigit** [comment]
I see. Okay, thank you for the information.
