### ISSUE TITLE
NEED_USER_AUTH_REQUIRED,Require user auth

### ISSUE THREAD

**Issue by Mrakobes666** [d-fi/releases#48]
Used new ARL's ones and the same

**Comment by nkeor** [comment]
Are you sure you got a _brand new_ arl? This error means the arl expired

**Comment by Mrakobes666** [comment]
I went through a few new ones and it worked, if there is an opportunity to share the source of your arl?

**Comment by nkeor** [comment]
Well the default arl comes from deezer.com, where else do you think it could come from?

Anyway, if this is fixed by using a new arl we can close this issue.
