### ISSUE TITLE
Latest version is not opening

### ISSUE THREAD

**Issue by verone0001** [d-fi/releases#49]
As title says, latest version isn't opening correctly for me. It just opens the console a couple seconds and then it automatically closes, showing the following before closing:

![image](https://user-images.githubusercontent.com/30376241/177225598-850d5634-70ab-4878-bae9-f4531ace5a23.png)

It isn't a false positive since I checked it. Any thoughts?

**Comment by nkeor** [comment]
have you tried with a fresh arl?

**Comment by verone0001** [comment]
Mind pointing how can I get one / refresh the already existent? I remember some versions ago probably from 2020 that I just used to open the executable and that was all.

**Comment by nkeor** [comment]
Here's a great guide: https://telegra.ph/How-to-get-Deezer-ARL-Token-07-17
then just run `d-fi -a ARL` where ARL is the token you got from the guide.

**Comment by verone0001** [comment]
Thanks! I remember using it to download Spotify songs, what happened to those?

**Comment by nkeor** [comment]
d-fi never downloads from spotify, it actually maps spotify isrcs (track ids) to deezer and download from there. So you need a Deezer ARL for Spotify downlaods anyway

**Comment by verone0001** [comment]
I see, well thanks for the tutorial! You can close the issue.

**Comment by nkeor** [comment]
You're welcome!
