### ISSUE TITLE
GETTING ALBUM PICTURE

### ISSUE THREAD

**Issue by ayDavidGitHere** [d-fi/releases#54]
How can i get the url to an album picture from the ALB_PICTURE property of api.getTrackInfo();

**Comment by nkeor** [comment]
Take a look at [`downloadAlbumCover`](https://github.com/d-fi/d-fi-core/blob/9e7f26007f2ee41bc17da6886d9f56358277b05a/src/metadata-writer/abumCover.ts#L18)

**Comment by ayDavidGitHere** [comment]
> Take a look at [`downloadAlbumCover`](https://github.com/d-fi/d-fi-core/blob/9e7f26007f2ee41bc17da6886d9f56358277b05a/src/metadata-writer/abumCover.ts#L18)

Thank you, I figured it out,
```
  let trackInfo = await api.getTrackInfo(song_id);
  let albumInfo = await api.getAlbumInfo(trackInfo.ALB_ID);
  let albumcoverurl = `https://e-cdns-images.dzcdn.net/images/cover/${trackInfo.ALB_PICTURE}/1000x1000-000000-80-0-0.jpg`;

```
This gave me what I need.
