### ISSUE TITLE
It... closes????

### ISSUE THREAD

**Issue by MettatonTheRobot-15** [d-fi/releases#55]
So a few milliseconds after I click on it to open it, it automatically closes. Very nice indeed.
WHAT?!

**Comment by nkeor** [comment]
There's probably some issue with the config file.
Try opening a CMD with by right-clicking on the folder while holding Shift, and run `d-fi.exe`.
That would help diagnose the issue.

**Comment by MettatonTheRobot-15** [comment]
Oops, sorry, now it works fine. Thank you.
