### ISSUE TITLE
Osx Ventura 13.4 Response code 416 (Requested Range Not Satisfiable)

### ISSUE THREAD

**Issue by Galvo87** [d-fi/releases#56]
I have d-fi running perfectly on other Osx machines (both Intel and ARM).
On a M2 MBP I keep getting `Response code 416 (Requested Range Not Satisfiable)` when trying to download.
I tried both with openssl1.1.1u and openssl3.3 without luck...
Any hint?

**Comment by nkeor** [comment]
You could try removing any d-fi_* cache files

**Comment by Galvo87** [comment]
@forkbomb9 that coupled with the right openssl version did the trick, thanks!
