### ISSUE TITLE
{ERROR} This album is not available on deezer!

### ISSUE THREAD

**Issue by nahuediaz96** [d-fi/releases#9]
Hi, im user of d-fi since 2019. But in the last days, all the songs that I want to download from spotify tell me that error.

Any solution?

d-fi.log = 
{"message":"Selected music quality: 1","level":"debug","timestamp":"2020-08-23T19:14:52.312Z"}
{"message":"Started download task: https://open.spotify.com/album/27wHXPMeHNnHJPTN5OfMeG?si=Glm5eVhPQPKgO3PPpbLelg","level":"debug","timestamp":"2020-08-23T19:14:56.226Z"}
{"error":"ALbum #27wHXPMeHNnHJPTN5OfMeG","message":"This album is not available on deezer!","level":"debug","timestamp":"2020-08-23T19:14:58.178Z"}

**Comment by sayem314** [comment]
Is this specific to this album or on all albums? Spotify tracks and albums are sourced from Deezer and not all songs are available.

**Comment by nahuediaz96** [comment]
This is happening to me with all the albums, and individual tracks that I want to download.

**Comment by sayem314** [comment]
Okay got it. I’m unable to debug this now since Spotify is not available in my place currently. I will update you within next few days!

**Comment by nahuediaz96** [comment]
Nice, thank you.

**Comment by sayem314** [comment]
Deezer seems to remove the UPC search feature for albums. A workaround can be done but I'm too busy now to do this. I will do this on v2 (maybe next year).

**Comment by sayem314** [comment]
Album support is now revived on v2 beta 3
